### ISSUE TITLE
FR: Allow to specify custom piped instance

### ISSUE THREAD

**Issue by samip5** [ai25/conduit#1]
Currently the instance selector doesn't allow to specify non public instance URLs.

**Comment by ai25** [comment]
This will be available when I add settings, at the moment they're not implemented. 
Meanwhile, you can set your custom instance manually in the console:
```
let preferences = JSON.parse(localStorage.preferences)
preferences.instance = {
    name:"your instance name",
    api_url:"https://your_instance_url",
    image_proxy_url:"https://your_proxy_url"
    } 
localStorage.preferences = JSON.stringify(preferences)
```
