### ISSUE TITLE
Copy YouTube UI Layout

### ISSUE THREAD

**Issue by arjpar** [ai25/conduit#4]
I think it would be useful to copy YouTube's UI -- as in the general layout/padding/margins/button placement/etc., not every single design element/texture/feel like ambient mode or material design if need be. The reason being is I think all the current alternative YouTube frontends are lacking in design, except ViewTube IMHO (which some like, some dislike); creating an interface that is similar to YouTube will be familiar to existing YouTube users and may attract users of Invidious/Piped/etc.

So far, I think conduit does a great job! Just a few elements need to be moved (different placement) and resized (padding, margins, etc).

I understand this project is a work in progress and other design goals need to be implemented first, as discussed in the README. I appreciate your consideration of my request.

**Comment by ai25** [comment]
As you said, the design is in the early stages and is not currently a main priority, other than issues that prevent usability. I am not interested in copying Youtube's layout exactly, but if you have specific pain points/flaws you want to point out, I am open to suggestions/PRs
