### ISSUE TITLE
Subscriptions don't get saved + feed settings

### ISSUE THREAD

**Issue by HexPum** [ai25/conduit#6]
when reloading the website, the feed is empty again.

Even when turning the feed on as the main page in the settings, it stays at trending, when reopening the website.

**Comment by ai25** [comment]
> when reloading the website, the feed is empty again.

did you create a room? if yes, make sure your browser supports OPFS. go to /debug to check

> Even when turning the feed on as the main page in the settings, it stays at trending, when reopening the website.

this is fixed
